### PR TITLE
Add a simple exponentially weighted moving average - fixes #6

### LINKED ISSUE #6: exponentially weighted moving average would provide more accurate "time left"
Instead of using the global average time per entry to calculate the remaining time, using EWMA would give more weight to recent times per entry and would likely provide a more accurate estimate.

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by harshavardhana** [comment]
@cheggaaa - unsure if you want it but i just thought lets give it a shot :-)

**Comment by cheggaaa** [comment]
Looks good! )
But i don't sure this works correct.
1. You have new EWMA object every 'write' call https://github.com/cheggaaa/pb/pull/47/files#diff-d4cff43ab09a9c56d49a047d8ed25163R246
2. When bar is finished we write elapsed time into timeLeftBox (changes not needed)

**Comment by cheggaaa** [comment]
Hm... look at curl progress for example ( https://github.com/bagder/curl/blob/master/lib/progress.c )
They store values in spans and calculate correct speed (and time) for last period.
I think without spans we can't get actual speed and and time...

**Comment by harshavardhana** [comment]
Rebased and fixed with the new changes..

**Comment by harshavardhana** [comment]
Oh i thought the 'left.String()' was the span. Let me see how this can be re-worked

**Comment by cheggaaa** [comment]
it's doesn't solve the problem
EWMA just smoothes values. We have not more accurate output

**Comment by cheggaaa** [comment]
we need to store values by periods..
spans = [[value1, time1], [value2, time2] ... ]
next we need calculate speed and time for every period and print it through EWMA

oh.. it's not easy)

**Comment by harshavardhana** [comment]
> spans = [[value1, time1], [value2, time2] ... ]

yes it looks like writing spans for every Write() or Read() we .. looks like not worth the effort. Good enough is good already :-)

**Comment by cheggaaa** [comment]
Sorry but now it seems pointless..
It becomes less accurate and more code)

**Comment by cheggaaa** [comment]
we can calculate average speed through ewma
and the' time left' through this speed

**Comment by harshavardhana** [comment]
> we can calculate average speed through ewma

yes that is do-able, let me rework it.

**Comment by cheggaaa** [comment]
could you make ewma-constants as private (first letter to lower)
and maybe ewma will work with ints (not float64)?

**Comment by harshavardhana** [comment]
> and maybe ewma will work with ints (not float64)?

float64 is used for division and accurate values so that we can round them off if needed later.

**Comment by harshavardhana** [comment]
Not pursuing this anymore, what we have in pb is good enough.

**Pull request closed without merging**
