### PR TITLE
Custom format

### PR DESCRIPTION
**Pull request by klaidliadon**
Adding strings delimited by \x00 to have colored bars.

Needs some review because the colored bar is slightly smaller.

### CODE REVIEW

**Comment by cheggaaa** [comment]
Sorry for delay

Bar does not use possible width of terminal.
It's because we don't cut special characters, just taking string length - https://github.com/cheggaaa/pb/blob/master/pb.go#L271

**Comment by klaidliadon** [comment]
I update the rune count, now the color bar works like a charm

**Comment by cheggaaa** [comment]
Yes! Now works good)
But how it will work on windows?

**Comment by klaidliadon** [comment]
The color library should be good for windows, I will make test if on a windows machine there different escapes sequence (for rune count)

**Comment by cheggaaa** [comment]
I look at this code https://github.com/mattn/go-colorable/blob/master/colorable_windows.go
And not sure how this regexp "\x1b\x5b[0-9]+\x6d" will work)
But anything, it's not breaking changes) Thanks!

**Comment by klaidliadon** [comment]
On my windows laptop seems to work fine

**Pull request merged**
