### PR TITLE
forupstream

### PR DESCRIPTION
**Pull request by drewis**

### CODE REVIEW

**Comment by cheggaaa** [comment]
I'm sorry for the delay.

You have panic when calling "Finish" twice. 
I think it's not good... maybe giving error, but not a panic.

**Comment by drewis** [comment]
I can submit another pull request with just the Units commit if you dont like the others

**Comment by cheggaaa** [comment]
Was merged two commits. Thankyou!

**Comment by cheggaaa** [comment]
Oops i missed your fixes)
Merged!

**Pull request merged**
