### PR TITLE
use uber-go/atomic.String for prefix/suffix race cdt

### PR DESCRIPTION
**Pull request by azr**
Howdy, had a race condition with prefix/postfix and write. Is it okay to add a dependency ? 

closes #138

### CODE REVIEW

**Comment by slomek** [comment]
Maybe it's better to use `"sync/atomic"` from standard library?

**Comment by cheggaaa** [comment]
Thank you for PR.

1. You can use [v2](https://github.com/cheggaaa/pb/tree/v2). That supports any strings and fully thread safe.

2. About this realization. I think we don't need ```atomic.String``` cause we already have the mutex. Just move [pb.mu.Lock() ](https://github.com/cheggaaa/pb/blob/master/pb.go#L402) above (before out = pb.prefix + ...) and wrap setters under mutex.

**Comment by azr** [comment]
Hey @cheggaaa, thanks for reviewing, here comes the mutex locked version of this:

**Comment by cheggaaa** [comment]
@azr Small notice. Can you make one lock in the `write` method? looks like it's will be cheaper and will not bring problems

**Comment by cheggaaa** [comment]
Thank you! Version is v1.0.26

**Comment by azr** [comment]
Yay !

**Pull request merged**
